### ISSUE TITLE
update to pytorch lightning 1.8.2

### ISSUE THREAD

**Issue by fcakyon** [devrimcavusoglu/torchrush#10]
@devrimcavusoglu 1.8.2'ye gecmemeiz icin bir sebebimiz var mi? 1.8.2'e gecince hata veren bir parca var mi?

https://github.com/devrimcavusoglu/torchrush-dev/blob/add462e7881802ec6f4c8e0cad1abd87779bb7b0/requirements.txt#L4

**Comment by devrimcavusoglu** [comment]
Tüm çalışmaları `1.7.7` ile yapmıştım, daha güncel bi versiyon ile deneme yapmadım, eğer trainer testinde problem yoksa bence geçebiliriz :+1:
