### ISSUE TITLE
add test docs

### ISSUE THREAD

**Issue by fcakyon** [devrimcavusoglu/torchrush#12]
@devrimcavusoglu hocam, readmeye testle ilgili de ufak bi baslik eklesek mi? 😅 nasil run ediyoruz testleri?

**Comment by devrimcavusoglu** [comment]
Ekleyelim hocam :+1: onu direk bizim conventiondan almıştım, `python tests/run_test.py` diyerek test edebilirsin, benzer şekilde, `python tests/run_code_style.py format` ile formatlayabilirsin. Eğer PYTHONPATH'e ekliyse project root bu şekilde, değilse aşağıdaki komutları kullanabilirsin:

```
python -m tests.run_tests
python -m tests.run_code_style format
```

2. opsiyon her türlü çalışacaktır.

**Comment by fcakyon** [comment]
> Ekleyelim hocam 👍 onu direk bizim conventiondan almıştım, `python tests/run_test.py` diyerek test edebilirsin, 

Soyle bir hata aliyorum:

```bash
Traceback (most recent call last):
  File "C:\Users\FCA\dev\torchrush-dev\tests\run_tests.py", line 1, in <module>
    from tests.utils import shell, validate_and_exit
ModuleNotFoundError: No module named 'tests'
```

**Comment by fcakyon** [comment]
> python -m tests.run_tests
> python -m tests.run_code_style format

Bu calisti evet 👍
