### ISSUE TITLE
how about `line_lenght=104` ?

### ISSUE THREAD

**Issue by fcakyon** [devrimcavusoglu/torchrush#21]
@devrimcavusoglu line length azaltmak hakkinda gorusun var mi? 110 olsa monitoru daha effektif kullanabiliriz gibi geliyor :) okunurlugu cok azaltir mi?

https://github.com/devrimcavusoglu/torchrush-dev/blob/89a3fc87d10658a98bb917832c3982ec331c1063/setup.cfg#L2

https://github.com/devrimcavusoglu/torchrush-dev/blob/89a3fc87d10658a98bb917832c3982ec331c1063/setup.cfg#L8

https://github.com/devrimcavusoglu/torchrush-dev/blob/89a3fc87d10658a98bb917832c3982ec331c1063/pyproject.toml#L2

**Comment by devrimcavusoglu** [comment]
👍

**Comment by devrimcavusoglu** [comment]
Closed by #31
