### ISSUE TITLE
changing main branch to `main`

### ISSUE THREAD

**Issue by fcakyon** [devrimcavusoglu/torchrush#22]
@devrimcavusoglu hocam master daha mi kolay geliyor sana? 😅 biz is yerinde hep main kullandigimiz icin alismis elim arada yanlis yere pushluyorum :D ama sana boyle daha kolaysa kalsin sorun degil 👌

**Comment by devrimcavusoglu** [comment]
Yoo ben main olmasını bekliyordum aslında, çünkü repo eski değil max 2 ay önce açmışımdır 😅

**Comment by devrimcavusoglu** [comment]
Default branch has been renamed to `main`.
