### ISSUE TITLE
gather init params and create a property named _config

### ISSUE THREAD

**Issue by fcakyon** [devrimcavusoglu/torchrush#5]
https://github.com/devrimcavusoglu/torchrush-dev/blob/ed1395c271a95ad50496258bd7052bb4c7fefb05/torchrush/model/base.py#L32

also include package version:

https://github.com/devrimcavusoglu/torchrush-dev/blob/019ec413af5bcd8b5fb98649c9bf5b944762c913/torchrush/__init__.py#L5

**Comment by devrimcavusoglu** [comment]
Closed by #8.
