### ISSUE TITLE
huggingface hubmixin yapisi eklenmesi

### ISSUE THREAD

**Issue by fcakyon** [devrimcavusoglu/torchrush#6]
https://github.com/huggingface/huggingface_hub/blob/9735536370137f49f6f6ca1cf6508b41c8ae8dd3/src/huggingface_hub/hub_mixin.py#L23

pytorch mixin referans alinabilir: 

https://github.com/huggingface/huggingface_hub/blob/9735536370137f49f6f6ca1cf6508b41c8ae8dd3/src/huggingface_hub/hub_mixin.py#L405

load ederken lightning doc bakilabilir:

https://pytorch-lightning.readthedocs.io/en/stable/common/checkpointing_basic.html

https://github.com/Lightning-AI/lightning/blob/3ea8903a325a148f1f26734d5006ddc04087b490/src/pytorch_lightning/core/saving.py#L60

**Comment by devrimcavusoglu** [comment]
upload models with a loader python script (e.g `rush.py`), ideal kullanım senaryosu aşağıdaki gibi olabilir (subject to change)

```python
rushModule.from_pretrained("fcakyon/dummy-rush-model", "AutoEncoder")	
```
